= TemplateMaker Project Documentation

----
Travis Build Status for Master Branch: [![Build Status](https://travis-ci.org/jnorthr/TemplateMaker.svg?branch=master)](https://travis-ci.com/jnorthr/TemplateMaker)
----
 
== Pre-requisites

1. Working internet connection
2. Installed Git client to copy/clone this repo
3. Ability to use terminal console
4. If no **projectname** value then pick ../$projectDir root folder name as it
5. Merge tasks from copyDocs into copyCore
6. Improve README
7. Write bash script to build project

== Purpose

This is a Gradle project for users who develop with Git, GitHub, Travis, Gradle and Groovy/Java/Scala. This clone includes gradle build tool wrapper and folder structure like maven/gradle so you don't need an installed gradle build tool.

Use this tool to construct a completely new skeleton set of files & folders for a new project. This layout is created within an existing folder directory on your local kit. New JVM-type source files are often mostly JVM-based languages, like java,groovy,scala,etc.


